# coding: utf-8
"""
Este módulo define um dicionário de descrições para os campos retornados
pela API de consultas do Portal Nacional de Contratações Públicas (PNCP).

O dicionário `DESCRICOES` organiza as descrições por alias de endpoint. Cada
chave de primeiro nível identifica um conjunto de campos relacionados a
determinado recurso: contratações, itens das contratações e resultados dos
itens. Os nomes dos campos seguem a nomenclatura utilizada pela API do
PNCP (incluindo campos aninhados com notação de ponto) e as descrições
fornecem um breve resumo do significado de cada campo conforme os
manuais oficiais do PNCP.

Campos que não se aplicam a determinado recurso ou para os quais não
existem dados adicionais no manual foram preenchidos com descrições
sintéticas baseadas no contexto de uso. Todas as descrições estão em
português, visto que a documentação oficial do PNCP também está nessa
língua.
"""

DESCRICOES: dict = {
    # Campos retornados pelo serviço de consulta de contratações (licitações
    # e contratações diretas) publicados no PNCP. Esses campos são
    # descritos no Manual das APIs de Consultas – Versão 1.0.
    "contratacoes": {
        "data.srp": "Indica se a contratação está enquadrada como Sistema de Registro de Preços (SRP); verdadeiro quando a contratação utiliza esse regime de aquisição",
        "data.orgaoEntidade": "Objeto que reúne os dados do órgão ou entidade responsável pela contratação",
        "data.orgaoEntidade.cnpj": "CNPJ do órgão ou entidade responsável pela contratação",
        "data.orgaoEntidade.razaoSocial": "Razão social do órgão ou entidade que realiza a contratação",
        "data.orgaoEntidade.poderId": "Código do poder a que pertence o órgão (L – Legislativo, E – Executivo, J – Judiciário)",
        "data.orgaoEntidade.esferaId": "Código da esfera administrativa do órgão (F – Federal, E – Estadual, M – Municipal, D – Distrital)",
        "data.anoCompra": "Ano em que a contratação foi realizada",
        "data.sequencialCompra": "Número sequencial gerado pelo PNCP quando a contratação foi inserida no sistema",
        "data.dataInclusao": "Data em que o registro da contratação foi incluído no PNCP",
        "data.dataPublicacaoPncp": "Data em que a contratação foi publicada no PNCP",
        "data.dataAtualizacao": "Data da última atualização do registro da contratação no PNCP",
        "data.numeroCompra": "Número da contratação no sistema de origem (por exemplo, o número do processo no órgão)",
        "data.unidadeOrgao": "Objeto com os dados da unidade administrativa do órgão responsável pela contratação",
        "data.unidadeOrgao.ufNome": "Nome da unidade federativa (estado) da unidade administrativa do órgão",
        "data.unidadeOrgao.codigoIbge": "Código IBGE do município da unidade administrativa do órgão",
        "data.unidadeOrgao.codigoUnidade": "Código da unidade administrativa pertencente ao órgão",
        "data.unidadeOrgao.nomeUnidade": "Nome da unidade administrativa pertencente ao órgão",
        "data.unidadeOrgao.ufSigla": "Sigla da unidade federativa (UF) da unidade administrativa do órgão",
        "data.unidadeOrgao.municipioNome": "Nome do município da unidade administrativa do órgão",
        "data.amparoLegal": "Objeto com os dados do amparo legal que fundamenta a contratação",
        "data.amparoLegal.descricao": "Descrição do amparo legal aplicável à contratação",
        "data.amparoLegal.nome": "Nome do amparo legal aplicável à contratação",
        "data.amparoLegal.codigo": "Código do amparo legal aplicável à contratação",
        "data.dataAberturaProposta": "Data e hora de abertura do período de recebimento de propostas (horário de Brasília)",
        "data.dataEncerramentoProposta": "Data e hora de encerramento do período de recebimento de propostas (horário de Brasília)",
        "data.informacaoComplementar": "Informações complementares sobre o objeto ou condições da contratação",
        "data.processo": "Número do processo de contratação no sistema de origem",
        "data.objetoCompra": "Descrição do objeto da contratação",
        "data.linkSistemaOrigem": "URL do portal ou sistema de origem para acompanhamento do processo da contratação",
        "data.justificativaPresencial": "Justificativa para escolha da modalidade presencial (quando aplicável)",
        "data.unidadeSubRogada": "Objeto com os dados da unidade administrativa do órgão subrogado (quando a contratação é realizada por outro órgão)",
        "data.unidadeSubRogada.ufNome": "Nome da unidade federativa da unidade administrativa subrogada",
        "data.unidadeSubRogada.codigoIbge": "Código IBGE do município da unidade administrativa subrogada",
        "data.unidadeSubRogada.codigoUnidade": "Código da unidade administrativa subrogada",
        "data.unidadeSubRogada.nomeUnidade": "Nome da unidade administrativa subrogada",
        "data.unidadeSubRogada.ufSigla": "Sigla da unidade federativa da unidade administrativa subrogada",
        "data.unidadeSubRogada.municipioNome": "Nome do município da unidade administrativa subrogada",
        "data.orgaoSubRogado": "Objeto com os dados do órgão ou entidade subrogado (contratação compartilhada)",
        "data.orgaoSubRogado.cnpj": "CNPJ do órgão ou entidade subrogado",
        "data.orgaoSubRogado.razaoSocial": "Razão social do órgão ou entidade subrogado",
        "data.orgaoSubRogado.poderId": "Código do poder ao qual pertence o órgão subrogado",
        "data.orgaoSubRogado.esferaId": "Código da esfera administrativa do órgão subrogado",
        "data.valorTotalHomologado": "Valor total homologado da contratação, com base nos resultados incluídos",
        "data.numeroControlePNCP": "Número de controle PNCP da contratação (identificador único da contratação no PNCP)",
        "data.modoDisputaId": "Código do modo de disputa utilizado na contratação (1 – Aberto, 2 – Fechado, 3 – Aberto‑Fechado)",
        "data.dataAtualizacaoGlobal": "Data da última atualização global do registro da contratação no PNCP",
        "data.linkProcessoEletronico": "URL do processo eletrônico relacionado à contratação (se disponível)",
        "data.modalidadeId": "Código da modalidade de contratação conforme tabela de domínios",
        "data.valorTotalEstimado": "Valor total estimado da contratação; retorna zero quando o orçamento é sigiloso e ainda não há resultado",
        "data.modalidadeNome": "Nome da modalidade de contratação",
        "data.modoDisputaNome": "Nome do modo de disputa utilizado na contratação",
        "data.tipoInstrumentoConvocatorioCodigo": "Código do instrumento convocatório utilizado na contratação",
        "data.tipoInstrumentoConvocatorioNome": "Nome do instrumento convocatório utilizado na contratação",
        "data.fontesOrcamentarias": "Lista de fontes orçamentárias que financiam a contratação",
        "data.fontesOrcamentarias.codigo": "Código da fonte orçamentária",
        "data.fontesOrcamentarias.nome": "Nome da fonte orçamentária",
        "data.fontesOrcamentarias.descricao": "Descrição da fonte orçamentária",
        "data.fontesOrcamentarias.dataInclusao": "Data em que a fonte orçamentária foi cadastrada",
        "data.situacaoCompraId": "Código da situação da contratação conforme tabela de domínios",
        "data.situacaoCompraNome": "Nome descritivo da situação da contratação",
        "data.usuarioNome": "Nome do usuário ou sistema que enviou a contratação ao PNCP",
    },
    # Campos retornados pelo serviço de consulta de itens das contratações PNCP
    # regidas pela Lei 14.133/2021.
    "itens": {
        "numeroItem": "Número sequencial do item dentro da contratação",
        "endpoint": "Caminho do endpoint utilizado para consultar os detalhes do item",
        "descricao": "Descrição detalhada do material ou serviço correspondente ao item",
        "materialOuServico": "Indica se o item refere‑se a um material (\"M\") ou a um serviço (\"S\")",
        "materialOuServicoNome": "Nome do material ou serviço associado ao item",
        "valorUnitarioEstimado": "Valor unitário estimado do item conforme informado na contratação",
        "valorTotal": "Valor total estimado do item (quantidade × valor unitário)",
        "quantidade": "Quantidade do item a ser contratada",
        "unidadeMedida": "Unidade de medida utilizada para quantificar o item",
        "orcamentoSigiloso": "Indicador se o orçamento do item é sigiloso (True/False)",
        "itemCategoriaId": "Identificador da categoria do item no PNCP",
        "itemCategoriaNome": "Nome da categoria do item",
        "patrimonio": "Indica se o item se refere a um bem patrimonial (True/False)",
        "codigoRegistroImobiliario": "Código de registro imobiliário, aplicável quando o item é um bem imóvel",
        "criterioJulgamentoId": "Identificador do critério de julgamento associado ao item",
        "criterioJulgamentoNome": "Nome do critério de julgamento associado ao item",
        "situacaoCompraItem": "Código da situação do item da compra (1 – Em andamento, 2 – Homologado, 3 – Anulado/Revogado/Cancelado, 4 – Deserto, 5 – Fracassado)",
        "situacaoCompraItemNome": "Descrição da situação do item da compra",
        "tipoBeneficio": "Código do tipo de benefício aplicado ao item (domínio definido pelo PNCP)",
        "tipoBeneficioNome": "Nome do tipo de benefício aplicado ao item",
        "incentivoProdutivoBasico": "Indicador de incentivo produtivo básico associado ao item (True/False)",
        "dataInclusao": "Data em que o item foi incluído no PNCP",
        "dataAtualizacao": "Data da última atualização do item no PNCP",
        "temResultado": "Indicador se existe resultado associado ao item (True/False)",
        "imagem": "URL ou referência a uma imagem ilustrativa do item",
        "aplicabilidadeMargemPreferenciaNormal": "Indica se se aplica margem de preferência normal ao item (True/False)",
        "aplicabilidadeMargemPreferenciaAdicional": "Indica se se aplica margem de preferência adicional ao item (True/False)",
        "percentualMargemPreferenciaNormal": "Percentual de margem de preferência normal aplicado ao item",
        "percentualMargemPreferenciaAdicional": "Percentual de margem de preferência adicional aplicado ao item",
        "ncmNbsCodigo": "Código NCM ou NBS (Nomenclatura Comum do Mercosul/Nomenclatura Brasileira de Serviços) do item",
        "ncmNbsDescricao": "Descrição da Nomenclatura Comum do Mercosul ou NBS do item",
        "catalogo.id": "Identificador do item no catálogo de bens ou serviços",
        "catalogo.nome": "Nome do item conforme cadastrado no catálogo",
        "catalogo.descricao": "Descrição do item conforme o catálogo",
        "catalogo.dataInclusao": "Data de inclusão do item no catálogo",
        "catalogo.dataAtualizacao": "Data de última atualização do item no catálogo",
        "catalogo.statusAtivo": "Indica se o item do catálogo está ativo (True/False)",
        "catalogo.url": "URL de referência para o item no catálogo oficial",
        "categoriaItemCatalogo.id": "Identificador da categoria do item no catálogo",
        "categoriaItemCatalogo.nome": "Nome da categoria do item no catálogo",
        "categoriaItemCatalogo.descricao": "Descrição da categoria do item no catálogo",
        "categoriaItemCatalogo.dataInclusao": "Data de inclusão da categoria no catálogo",
        "categoriaItemCatalogo.dataAtualizacao": "Data de atualização da categoria no catálogo",
        "categoriaItemCatalogo.statusAtivo": "Indica se a categoria do catálogo está ativa (True/False)",
        "catalogoCodigoItem": "Código do item no catálogo utilizado pela contratação",
        "informacaoComplementar": "Informações complementares sobre o item da contratação",
    },
    # Campos retornados pelo serviço de consulta de resultados dos itens das
    # contratações PNCP. Os nomes e descrições foram extraídos do manual
    # oficial.
    "resultados_itens": {
        "numeroControlePNCPCompra": "Número de controle PNCP da contratação a que o item pertence",
        "numeroItem": "Número do item na contratação",
        "endpoint": "Caminho do endpoint utilizado para consultar detalhes do resultado do item",
        "sequencialResultado": "Número sequencial do resultado associado ao item",
        "situacaoCompraItemResultadoId": "Identificador da situação do item no resultado de compra",
        "situacaoCompraItemResultadoNome": "Nome descritivo da situação do item no resultado de compra",
        "dataInclusao": "Data de inclusão do resultado do item no PNCP",
        "dataAtualizacao": "Data de última atualização do resultado do item no PNCP",
        "niFornecedor": "Número de Identificação Fiscal do fornecedor (CPF ou CNPJ)",
        "nomeRazaoSocialFornecedor": "Nome ou razão social do fornecedor vencedor do item",
        "tipoPessoa": "Tipo de pessoa do fornecedor (física ou jurídica)",
        "porteFornecedorId": "Identificador do porte do fornecedor (micro, pequena, média ou grande empresa)",
        "porteFornecedorNome": "Nome do porte do fornecedor",
        "naturezaJuridicaId": "Identificador da natureza jurídica do fornecedor",
        "naturezaJuridicaNome": "Nome da natureza jurídica do fornecedor",
        "codigoPais": "Código do país do fornecedor",
        "quantidadeHomologada": "Quantidade homologada do item no resultado",
        "valorUnitarioHomologado": "Valor unitário homologado do item",
        "valorTotalHomologado": "Valor total homologado do item no resultado",
        "percentualDesconto": "Percentual de desconto oferecido pelo fornecedor vencedor",
        "paisOrigemProdutoServico.id": "Código do país de origem do produto ou serviço fornecido",
        "paisOrigemProdutoServico.nome": "Nome do país de origem do produto ou serviço",
        "moedaEstrangeira.id": "Identificador da moeda estrangeira utilizada no resultado (quando aplicável)",
        "moedaEstrangeira.simbolo": "Símbolo da moeda estrangeira utilizada",
        "moedaEstrangeira.nome": "Nome da moeda estrangeira utilizada",
        "timezoneCotacaoMoedaEstrangeira": "Fuso horário de referência da cotação da moeda estrangeira",
        "valorNominalMoedaEstrangeira": "Valor nominal do item em moeda estrangeira",
        "dataCotacaoMoedaEstrangeira": "Data em que foi realizada a cotação da moeda estrangeira",
        "aplicacaoMargemPreferencia": "Indicador se foi aplicada margem de preferência na contratação (True/False)",
        "amparoLegalMargemPreferencia.id": "Identificador do amparo legal relacionado à aplicação da margem de preferência",
        "amparoLegalMargemPreferencia.nome": "Nome do amparo legal relacionado à aplicação da margem de preferência",
        "amparoLegalMargemPreferencia.descricao": "Descrição do amparo legal relacionado à aplicação da margem de preferência",
        "amparoLegalMargemPreferencia.statusAtivo": "Indica se o amparo legal de margem de preferência está ativo",
        "aplicacaoBeneficioMeEpp": "Indicador se foi concedido benefício específico para ME/EPP (Micro e Pequenas Empresas)",
        "aplicacaoCriterioDesempate": "Indicador se foi aplicado critério de desempate conforme a legislação",
        "amparoLegalCriterioDesempate.id": "Identificador do amparo legal relacionado ao critério de desempate",
        "amparoLegalCriterioDesempate.nome": "Nome do amparo legal relacionado ao critério de desempate",
        "amparoLegalCriterioDesempate.descricao": "Descrição do amparo legal relacionado ao critério de desempate",
        "amparoLegalCriterioDesempate.statusAtivo": "Indica se o amparo legal do critério de desempate está ativo",
        "indicadorSubcontratacao": "Indica se há subcontratação no resultado do item (True/False)",
        "ordemClassificacaoSrp": "Ordem de classificação do fornecedor no Sistema de Registro de Preços (SRP)",
        "dataResultado": "Data do resultado homologado para o item no PNCP",
        "dataCancelamento": "Data de cancelamento do resultado do item (se houver)",
        "motivoCancelamento": "Motivo do cancelamento do resultado do item (quando cancelado)",
    },
}
