-- Conectar ao banco de dados desejado
\c medicamentos-transparentes;

-- Criar tabelas dentro do esquema
CREATE TABLE catalogo (
    codigo_classe SMALLINT NOT NULL,
    nome_classe VARCHAR(100) NOT NULL,
    codigo_pdm INTEGER NOT NULL,
    nome_pdm VARCHAR(100) NOT NULL,
    codigo_item INTEGER PRIMARY KEY,
    nome_item VARCHAR(1000) NOT NULL,
    item_suspenso BOOLEAN,
    item_ativo BOOLEAN,
    item_sustentavel BOOLEAN,
    características JSONB NOT NULL,
    caracteristicas_ocds JSONB,
    unidades_fornecimento JSONB NOT NULL,
    data_insercao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN catalogo.caracteristicas_ocds IS
    'Atributos técnicos do medicamento mapeados para o padrão OCDS.';

CREATE TABLE contratante (
    cnpj BIGINT,
    razao_social VARCHAR(1000) NOT NULL,
    esfera CHAR(1),
    poder CHAR(1),
    codigo_unidade VARCHAR(100) NOT NULL,
    nome_unidade VARCHAR(1000) NOT NULL,
    codigo_ibge_municipio INTEGER,
    nome_municipio VARCHAR(100),
    sigla_uf CHAR(2),
    nome_uf VARCHAR(100),
    data_insercao TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (cnpj, codigo_unidade)
);

CREATE TABLE fornecedor (
    ni VARCHAR(100) PRIMARY KEY,
    nome VARCHAR(1000) NOT NULL,
    codigo_pais CHAR(3),
    tipo_pessoa CHAR(2),
    codigo_porte SMALLINT,
    nome_porte VARCHAR(100),
    codigo_natureza_juridica VARCHAR(10),
    nome_natureza_juridica VARCHAR(1000),
    data_insercao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contratacao (
    numero_controle_pncp VARCHAR(30) PRIMARY KEY,
    ano_compra SMALLINT NOT NULL,
    sequencial_compra INTEGER NOT NULL,
    objeto_compra TEXT,
    data_abertura_proposta TIMESTAMP,
    data_encerramento_proposta TIMESTAMP,
    valor_estimado_compra NUMERIC,
    valor_homologado_compra NUMERIC,
    srp BOOLEAN,
    codigo_tipo_instrumento_convocatorio SMALLINT NOT NULL,
    nome_tipo_instrumento_convocatorio VARCHAR(100) NOT NULL,
    codigo_modalidade SMALLINT NOT NULL,
    nome_modalidade VARCHAR(100) NOT NULL,
    codigo_amparo_legal SMALLINT NOT NULL,
    nome_amparo_legal VARCHAR(100) NOT NULL,
    codigo_modo_disputa SMALLINT NOT NULL,
    nome_modo_disputa VARCHAR(100) NOT NULL,
    data_insercao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE item_homologado (
    numero_controle_pncp VARCHAR(30),
    codigo_item_catalogo INT,
    cnpj_contratante BIGINT,
    codigo_unidade_contratante VARCHAR(100),
    cnpj_contratante_subrogado BIGINT,
    codigo_unidade_contratante_subrogado VARCHAR(100),
    ni_fornecedor VARCHAR(100),
    numero_item INTEGER NOT NULL,
    descricao TEXT,
    unidade_medida VARCHAR(1000),
    material_servico CHAR(1),
    codigo_categoria_item INTEGER,
    nome_categoria_item VARCHAR(1000),
    codigo_catalogo INT,
    nome_catalogo VARCHAR(100),
    codigo_categoria_item_catalogo INT,
    nome_categoria_item_catalogo VARCHAR(1000),
    codigo_item_catalogo_pncp VARCHAR(100),
    codigo_ncm_nbs INTEGER,
    descricao_ncm_nbs VARCHAR(1000),
    codigo_criterio_julgamento SMALLINT NOT NULL, 
    nome_criterio_julgamento VARCHAR(100) NOT NULL,
    codigo_situacao_item INTEGER,
    nome_situacao_item VARCHAR(100),
    codigo_tipo_beneficio SMALLINT,
    nome_tipo_beneficio VARCHAR(100),
    orcamento_sigiloso BOOLEAN,
    valor_unitario_estimado NUMERIC,
    valor_total_estimado NUMERIC,
    quantidade_estimada INTEGER,
    codigo_situacao_resultado SMALLINT,
    nome_situacao_resultado VARCHAR(100),
    valor_unitario_homologado NUMERIC,
    valor_total_homologado NUMERIC,
    quantidade_homologada INTEGER,
    moeda_estrangeira CHAR(3),
    valor_nominal_moeda_estrangeira NUMERIC,
    data_resultado TIMESTAMP,
    data_cancelamento TIMESTAMP,
    motivo_cancelamento VARCHAR(1000),
    url_api VARCHAR(1000) NOT NULL,
    url_pncp VARCHAR(1000) NOT NULL,
    data_insercao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (numero_controle_pncp, numero_item),
    FOREIGN KEY (numero_controle_pncp) REFERENCES contratacao (numero_controle_pncp) ON DELETE RESTRICT,
    FOREIGN KEY (codigo_item_catalogo) REFERENCES catalogo (codigo_item) ON DELETE RESTRICT,
    FOREIGN KEY (cnpj_contratante, codigo_unidade_contratante) REFERENCES contratante (cnpj, codigo_unidade) ON DELETE RESTRICT,
    FOREIGN KEY (cnpj_contratante_subrogado, codigo_unidade_contratante_subrogado) REFERENCES contratante (cnpj, codigo_unidade) ON DELETE SET NULL,
    FOREIGN KEY (ni_fornecedor) REFERENCES fornecedor (ni) ON DELETE RESTRICT
);

CREATE TABLE item_licitado (
    numero_controle_pncp VARCHAR(30) NOT NULL,
    codigo_item_catalogo INT NOT NULL,
    cnpj_contratante BIGINT NOT NULL,
    codigo_unidade_contratante VARCHAR(100) NOT NULL,
    cnpj_contratante_subrogado BIGINT,
    codigo_unidade_contratante_subrogado VARCHAR(100),
    numero_item INTEGER NOT NULL,
    descricao TEXT,
    unidade_medida VARCHAR(1000),
    material_servico CHAR(1),
    codigo_categoria_item INTEGER,
    nome_categoria_item VARCHAR(1000),
    codigo_catalogo INT,
    nome_catalogo VARCHAR(100),
    codigo_categoria_item_catalogo INT,
    nome_categoria_item_catalogo VARCHAR(1000),
    codigo_item_catalogo_pncp VARCHAR(100),
    codigo_ncm_nbs INTEGER,
    descricao_ncm_nbs VARCHAR(1000),
    codigo_criterio_julgamento SMALLINT NOT NULL, 
    nome_criterio_julgamento VARCHAR(100) NOT NULL,
    codigo_situacao_item INTEGER,
    nome_situacao_item VARCHAR(100),
    codigo_tipo_beneficio SMALLINT,
    nome_tipo_beneficio VARCHAR(100),
    orcamento_sigiloso BOOLEAN,
    valor_unitario_estimado NUMERIC,
    valor_total_estimado NUMERIC,
    quantidade_estimada INTEGER,
    url_api VARCHAR(1000) NOT NULL,
    url_pncp VARCHAR(1000) NOT NULL,
    data_insercao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (numero_controle_pncp, numero_item)
);
